/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabalheConoscoRouteImport } from './routes/trabalhe-conosco'
import { Route as SejaParceiroRouteImport } from './routes/seja-parceiro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ConvitePreviewInvitationIdRouteImport } from './routes/convite.preview.$invitationId'
import { Route as ConvitePadrinhoTokenRouteImport } from './routes/convite.padrinho.$token'
import { Route as AuthenticatedAppUpgradesRouteImport } from './routes/_authenticated/app/upgrades'
import { Route as AuthenticatedAppReferenciasRouteImport } from './routes/_authenticated/app/referencias'
import { Route as AuthenticatedAppPortfolioRouteImport } from './routes/_authenticated/app/portfolio'
import { Route as AuthenticatedAppPendenciasRouteImport } from './routes/_authenticated/app/pendencias'
import { Route as AuthenticatedAppParceirosRouteImport } from './routes/_authenticated/app/parceiros'
import { Route as AuthenticatedAppEbookRouteImport } from './routes/_authenticated/app/ebook'
import { Route as AuthenticatedAppDicasRouteImport } from './routes/_authenticated/app/dicas'
import { Route as AuthenticatedAppConvitesRouteImport } from './routes/_authenticated/app/convites'
import { Route as AuthenticatedAppChecklistRouteImport } from './routes/_authenticated/app/checklist'
import { Route as AuthenticatedAppCardapiosRouteImport } from './routes/_authenticated/app/cardapios'
import { Route as AuthenticatedAdminUpgradesRouteImport } from './routes/_authenticated/admin/upgrades'
import { Route as AuthenticatedAdminReferenciasRouteImport } from './routes/_authenticated/admin/referencias'
import { Route as AuthenticatedAdminPortfolioRouteImport } from './routes/_authenticated/admin/portfolio'
import { Route as AuthenticatedAdminParceirosRouteImport } from './routes/_authenticated/admin/parceiros'
import { Route as AuthenticatedAdminNotificacoesRouteImport } from './routes/_authenticated/admin/notificacoes'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin/leads'
import { Route as AuthenticatedAdminInteressesRouteImport } from './routes/_authenticated/admin/interesses'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/admin/eventos'
import { Route as AuthenticatedAdminEbooksRouteImport } from './routes/_authenticated/admin/ebooks'
import { Route as AuthenticatedAdminDicasRouteImport } from './routes/_authenticated/admin/dicas'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin/clientes'
import { Route as AuthenticatedAdminCardapiosRouteImport } from './routes/_authenticated/admin/cardapios'
import { Route as AuthenticatedAdminAcessosRouteImport } from './routes/_authenticated/admin/acessos'
import { Route as AuthenticatedAdminLeadsIndexRouteImport } from './routes/_authenticated/admin/leads.index'
import { Route as AuthenticatedAdminConvitesIndexRouteImport } from './routes/_authenticated/admin/convites.index'
import { Route as AuthenticatedAdminChecklistIndexRouteImport } from './routes/_authenticated/admin/checklist.index'
import { Route as AuthenticatedAdminLeadsParceirosRouteImport } from './routes/_authenticated/admin/leads.parceiros'
import { Route as AuthenticatedAdminLeadsIntegracoesRouteImport } from './routes/_authenticated/admin/leads.integracoes'
import { Route as AuthenticatedAdminLeadsFormularioRouteImport } from './routes/_authenticated/admin/leads.formulario'
import { Route as AuthenticatedAdminLeadsCandidaturasRouteImport } from './routes/_authenticated/admin/leads.candidaturas'
import { Route as AuthenticatedAdminConvitesEventIdRouteImport } from './routes/_authenticated/admin/convites.$eventId'
import { Route as AuthenticatedAdminChecklistEventIdRouteImport } from './routes/_authenticated/admin/checklist.$eventId'
import { Route as AuthenticatedAdminLeadsFormularioIndexRouteImport } from './routes/_authenticated/admin/leads.formulario.index'
import { Route as AuthenticatedAdminLeadsFormularioVisualRouteImport } from './routes/_authenticated/admin/leads.formulario.visual'
import { Route as AuthenticatedAdminLeadsFormularioSimuladorRouteImport } from './routes/_authenticated/admin/leads.formulario.simulador'
import { Route as AuthenticatedAdminLeadsFormularioScoreRouteImport } from './routes/_authenticated/admin/leads.formulario.score'
import { Route as AuthenticatedAdminLeadsFormularioPixelsRouteImport } from './routes/_authenticated/admin/leads.formulario.pixels'
import { Route as AuthenticatedAdminLeadsFormularioDiagnosticoRouteImport } from './routes/_authenticated/admin/leads.formulario.diagnostico'

const TrabalheConoscoRoute = TrabalheConoscoRouteImport.update({
  id: '/trabalhe-conosco',
  path: '/trabalhe-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const SejaParceiroRoute = SejaParceiroRouteImport.update({
  id: '/seja-parceiro',
  path: '/seja-parceiro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ConvitePreviewInvitationIdRoute =
  ConvitePreviewInvitationIdRouteImport.update({
    id: '/convite/preview/$invitationId',
    path: '/convite/preview/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConvitePadrinhoTokenRoute = ConvitePadrinhoTokenRouteImport.update({
  id: '/convite/padrinho/$token',
  path: '/convite/padrinho/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppUpgradesRoute =
  AuthenticatedAppUpgradesRouteImport.update({
    id: '/upgrades',
    path: '/upgrades',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReferenciasRoute =
  AuthenticatedAppReferenciasRouteImport.update({
    id: '/referencias',
    path: '/referencias',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPortfolioRoute =
  AuthenticatedAppPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPendenciasRoute =
  AuthenticatedAppPendenciasRouteImport.update({
    id: '/pendencias',
    path: '/pendencias',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppParceirosRoute =
  AuthenticatedAppParceirosRouteImport.update({
    id: '/parceiros',
    path: '/parceiros',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEbookRoute = AuthenticatedAppEbookRouteImport.update({
  id: '/ebook',
  path: '/ebook',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDicasRoute = AuthenticatedAppDicasRouteImport.update({
  id: '/dicas',
  path: '/dicas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppConvitesRoute =
  AuthenticatedAppConvitesRouteImport.update({
    id: '/convites',
    path: '/convites',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChecklistRoute =
  AuthenticatedAppChecklistRouteImport.update({
    id: '/checklist',
    path: '/checklist',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCardapiosRoute =
  AuthenticatedAppCardapiosRouteImport.update({
    id: '/cardapios',
    path: '/cardapios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminUpgradesRoute =
  AuthenticatedAdminUpgradesRouteImport.update({
    id: '/upgrades',
    path: '/upgrades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReferenciasRoute =
  AuthenticatedAdminReferenciasRouteImport.update({
    id: '/referencias',
    path: '/referencias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPortfolioRoute =
  AuthenticatedAdminPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParceirosRoute =
  AuthenticatedAdminParceirosRouteImport.update({
    id: '/parceiros',
    path: '/parceiros',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificacoesRoute =
  AuthenticatedAdminNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInteressesRoute =
  AuthenticatedAdminInteressesRouteImport.update({
    id: '/interesses',
    path: '/interesses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEbooksRoute =
  AuthenticatedAdminEbooksRouteImport.update({
    id: '/ebooks',
    path: '/ebooks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDicasRoute = AuthenticatedAdminDicasRouteImport.update({
  id: '/dicas',
  path: '/dicas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCardapiosRoute =
  AuthenticatedAdminCardapiosRouteImport.update({
    id: '/cardapios',
    path: '/cardapios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAcessosRoute =
  AuthenticatedAdminAcessosRouteImport.update({
    id: '/acessos',
    path: '/acessos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsIndexRoute =
  AuthenticatedAdminLeadsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminLeadsRoute,
  } as any)
const AuthenticatedAdminConvitesIndexRoute =
  AuthenticatedAdminConvitesIndexRouteImport.update({
    id: '/convites/',
    path: '/convites/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChecklistIndexRoute =
  AuthenticatedAdminChecklistIndexRouteImport.update({
    id: '/checklist/',
    path: '/checklist/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsParceirosRoute =
  AuthenticatedAdminLeadsParceirosRouteImport.update({
    id: '/parceiros',
    path: '/parceiros',
    getParentRoute: () => AuthenticatedAdminLeadsRoute,
  } as any)
const AuthenticatedAdminLeadsIntegracoesRoute =
  AuthenticatedAdminLeadsIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedAdminLeadsRoute,
  } as any)
const AuthenticatedAdminLeadsFormularioRoute =
  AuthenticatedAdminLeadsFormularioRouteImport.update({
    id: '/formulario',
    path: '/formulario',
    getParentRoute: () => AuthenticatedAdminLeadsRoute,
  } as any)
const AuthenticatedAdminLeadsCandidaturasRoute =
  AuthenticatedAdminLeadsCandidaturasRouteImport.update({
    id: '/candidaturas',
    path: '/candidaturas',
    getParentRoute: () => AuthenticatedAdminLeadsRoute,
  } as any)
const AuthenticatedAdminConvitesEventIdRoute =
  AuthenticatedAdminConvitesEventIdRouteImport.update({
    id: '/convites/$eventId',
    path: '/convites/$eventId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChecklistEventIdRoute =
  AuthenticatedAdminChecklistEventIdRouteImport.update({
    id: '/checklist/$eventId',
    path: '/checklist/$eventId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsFormularioIndexRoute =
  AuthenticatedAdminLeadsFormularioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminLeadsFormularioRoute,
  } as any)
const AuthenticatedAdminLeadsFormularioVisualRoute =
  AuthenticatedAdminLeadsFormularioVisualRouteImport.update({
    id: '/visual',
    path: '/visual',
    getParentRoute: () => AuthenticatedAdminLeadsFormularioRoute,
  } as any)
const AuthenticatedAdminLeadsFormularioSimuladorRoute =
  AuthenticatedAdminLeadsFormularioSimuladorRouteImport.update({
    id: '/simulador',
    path: '/simulador',
    getParentRoute: () => AuthenticatedAdminLeadsFormularioRoute,
  } as any)
const AuthenticatedAdminLeadsFormularioScoreRoute =
  AuthenticatedAdminLeadsFormularioScoreRouteImport.update({
    id: '/score',
    path: '/score',
    getParentRoute: () => AuthenticatedAdminLeadsFormularioRoute,
  } as any)
const AuthenticatedAdminLeadsFormularioPixelsRoute =
  AuthenticatedAdminLeadsFormularioPixelsRouteImport.update({
    id: '/pixels',
    path: '/pixels',
    getParentRoute: () => AuthenticatedAdminLeadsFormularioRoute,
  } as any)
const AuthenticatedAdminLeadsFormularioDiagnosticoRoute =
  AuthenticatedAdminLeadsFormularioDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedAdminLeadsFormularioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/seja-parceiro': typeof SejaParceiroRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/convite/$token': typeof ConviteTokenRoute
  '/admin/acessos': typeof AuthenticatedAdminAcessosRoute
  '/admin/cardapios': typeof AuthenticatedAdminCardapiosRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/dicas': typeof AuthenticatedAdminDicasRoute
  '/admin/ebooks': typeof AuthenticatedAdminEbooksRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/interesses': typeof AuthenticatedAdminInteressesRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRouteWithChildren
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/parceiros': typeof AuthenticatedAdminParceirosRoute
  '/admin/portfolio': typeof AuthenticatedAdminPortfolioRoute
  '/admin/referencias': typeof AuthenticatedAdminReferenciasRoute
  '/admin/upgrades': typeof AuthenticatedAdminUpgradesRoute
  '/app/cardapios': typeof AuthenticatedAppCardapiosRoute
  '/app/checklist': typeof AuthenticatedAppChecklistRoute
  '/app/convites': typeof AuthenticatedAppConvitesRoute
  '/app/dicas': typeof AuthenticatedAppDicasRoute
  '/app/ebook': typeof AuthenticatedAppEbookRoute
  '/app/parceiros': typeof AuthenticatedAppParceirosRoute
  '/app/pendencias': typeof AuthenticatedAppPendenciasRoute
  '/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/app/referencias': typeof AuthenticatedAppReferenciasRoute
  '/app/upgrades': typeof AuthenticatedAppUpgradesRoute
  '/convite/padrinho/$token': typeof ConvitePadrinhoTokenRoute
  '/convite/preview/$invitationId': typeof ConvitePreviewInvitationIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/admin/checklist/$eventId': typeof AuthenticatedAdminChecklistEventIdRoute
  '/admin/convites/$eventId': typeof AuthenticatedAdminConvitesEventIdRoute
  '/admin/leads/candidaturas': typeof AuthenticatedAdminLeadsCandidaturasRoute
  '/admin/leads/formulario': typeof AuthenticatedAdminLeadsFormularioRouteWithChildren
  '/admin/leads/integracoes': typeof AuthenticatedAdminLeadsIntegracoesRoute
  '/admin/leads/parceiros': typeof AuthenticatedAdminLeadsParceirosRoute
  '/admin/checklist/': typeof AuthenticatedAdminChecklistIndexRoute
  '/admin/convites/': typeof AuthenticatedAdminConvitesIndexRoute
  '/admin/leads/': typeof AuthenticatedAdminLeadsIndexRoute
  '/admin/leads/formulario/diagnostico': typeof AuthenticatedAdminLeadsFormularioDiagnosticoRoute
  '/admin/leads/formulario/pixels': typeof AuthenticatedAdminLeadsFormularioPixelsRoute
  '/admin/leads/formulario/score': typeof AuthenticatedAdminLeadsFormularioScoreRoute
  '/admin/leads/formulario/simulador': typeof AuthenticatedAdminLeadsFormularioSimuladorRoute
  '/admin/leads/formulario/visual': typeof AuthenticatedAdminLeadsFormularioVisualRoute
  '/admin/leads/formulario/': typeof AuthenticatedAdminLeadsFormularioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/seja-parceiro': typeof SejaParceiroRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/admin/acessos': typeof AuthenticatedAdminAcessosRoute
  '/admin/cardapios': typeof AuthenticatedAdminCardapiosRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/dicas': typeof AuthenticatedAdminDicasRoute
  '/admin/ebooks': typeof AuthenticatedAdminEbooksRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/interesses': typeof AuthenticatedAdminInteressesRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/parceiros': typeof AuthenticatedAdminParceirosRoute
  '/admin/portfolio': typeof AuthenticatedAdminPortfolioRoute
  '/admin/referencias': typeof AuthenticatedAdminReferenciasRoute
  '/admin/upgrades': typeof AuthenticatedAdminUpgradesRoute
  '/app/cardapios': typeof AuthenticatedAppCardapiosRoute
  '/app/checklist': typeof AuthenticatedAppChecklistRoute
  '/app/convites': typeof AuthenticatedAppConvitesRoute
  '/app/dicas': typeof AuthenticatedAppDicasRoute
  '/app/ebook': typeof AuthenticatedAppEbookRoute
  '/app/parceiros': typeof AuthenticatedAppParceirosRoute
  '/app/pendencias': typeof AuthenticatedAppPendenciasRoute
  '/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/app/referencias': typeof AuthenticatedAppReferenciasRoute
  '/app/upgrades': typeof AuthenticatedAppUpgradesRoute
  '/convite/padrinho/$token': typeof ConvitePadrinhoTokenRoute
  '/convite/preview/$invitationId': typeof ConvitePreviewInvitationIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/admin/checklist/$eventId': typeof AuthenticatedAdminChecklistEventIdRoute
  '/admin/convites/$eventId': typeof AuthenticatedAdminConvitesEventIdRoute
  '/admin/leads/candidaturas': typeof AuthenticatedAdminLeadsCandidaturasRoute
  '/admin/leads/integracoes': typeof AuthenticatedAdminLeadsIntegracoesRoute
  '/admin/leads/parceiros': typeof AuthenticatedAdminLeadsParceirosRoute
  '/admin/checklist': typeof AuthenticatedAdminChecklistIndexRoute
  '/admin/convites': typeof AuthenticatedAdminConvitesIndexRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsIndexRoute
  '/admin/leads/formulario/diagnostico': typeof AuthenticatedAdminLeadsFormularioDiagnosticoRoute
  '/admin/leads/formulario/pixels': typeof AuthenticatedAdminLeadsFormularioPixelsRoute
  '/admin/leads/formulario/score': typeof AuthenticatedAdminLeadsFormularioScoreRoute
  '/admin/leads/formulario/simulador': typeof AuthenticatedAdminLeadsFormularioSimuladorRoute
  '/admin/leads/formulario/visual': typeof AuthenticatedAdminLeadsFormularioVisualRoute
  '/admin/leads/formulario': typeof AuthenticatedAdminLeadsFormularioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/seja-parceiro': typeof SejaParceiroRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/convite/$token': typeof ConviteTokenRoute
  '/_authenticated/admin/acessos': typeof AuthenticatedAdminAcessosRoute
  '/_authenticated/admin/cardapios': typeof AuthenticatedAdminCardapiosRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/dicas': typeof AuthenticatedAdminDicasRoute
  '/_authenticated/admin/ebooks': typeof AuthenticatedAdminEbooksRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/_authenticated/admin/interesses': typeof AuthenticatedAdminInteressesRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRouteWithChildren
  '/_authenticated/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/_authenticated/admin/parceiros': typeof AuthenticatedAdminParceirosRoute
  '/_authenticated/admin/portfolio': typeof AuthenticatedAdminPortfolioRoute
  '/_authenticated/admin/referencias': typeof AuthenticatedAdminReferenciasRoute
  '/_authenticated/admin/upgrades': typeof AuthenticatedAdminUpgradesRoute
  '/_authenticated/app/cardapios': typeof AuthenticatedAppCardapiosRoute
  '/_authenticated/app/checklist': typeof AuthenticatedAppChecklistRoute
  '/_authenticated/app/convites': typeof AuthenticatedAppConvitesRoute
  '/_authenticated/app/dicas': typeof AuthenticatedAppDicasRoute
  '/_authenticated/app/ebook': typeof AuthenticatedAppEbookRoute
  '/_authenticated/app/parceiros': typeof AuthenticatedAppParceirosRoute
  '/_authenticated/app/pendencias': typeof AuthenticatedAppPendenciasRoute
  '/_authenticated/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/_authenticated/app/referencias': typeof AuthenticatedAppReferenciasRoute
  '/_authenticated/app/upgrades': typeof AuthenticatedAppUpgradesRoute
  '/convite/padrinho/$token': typeof ConvitePadrinhoTokenRoute
  '/convite/preview/$invitationId': typeof ConvitePreviewInvitationIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/admin/checklist/$eventId': typeof AuthenticatedAdminChecklistEventIdRoute
  '/_authenticated/admin/convites/$eventId': typeof AuthenticatedAdminConvitesEventIdRoute
  '/_authenticated/admin/leads/candidaturas': typeof AuthenticatedAdminLeadsCandidaturasRoute
  '/_authenticated/admin/leads/formulario': typeof AuthenticatedAdminLeadsFormularioRouteWithChildren
  '/_authenticated/admin/leads/integracoes': typeof AuthenticatedAdminLeadsIntegracoesRoute
  '/_authenticated/admin/leads/parceiros': typeof AuthenticatedAdminLeadsParceirosRoute
  '/_authenticated/admin/checklist/': typeof AuthenticatedAdminChecklistIndexRoute
  '/_authenticated/admin/convites/': typeof AuthenticatedAdminConvitesIndexRoute
  '/_authenticated/admin/leads/': typeof AuthenticatedAdminLeadsIndexRoute
  '/_authenticated/admin/leads/formulario/diagnostico': typeof AuthenticatedAdminLeadsFormularioDiagnosticoRoute
  '/_authenticated/admin/leads/formulario/pixels': typeof AuthenticatedAdminLeadsFormularioPixelsRoute
  '/_authenticated/admin/leads/formulario/score': typeof AuthenticatedAdminLeadsFormularioScoreRoute
  '/_authenticated/admin/leads/formulario/simulador': typeof AuthenticatedAdminLeadsFormularioSimuladorRoute
  '/_authenticated/admin/leads/formulario/visual': typeof AuthenticatedAdminLeadsFormularioVisualRoute
  '/_authenticated/admin/leads/formulario/': typeof AuthenticatedAdminLeadsFormularioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leads'
    | '/login'
    | '/seja-parceiro'
    | '/trabalhe-conosco'
    | '/admin'
    | '/app'
    | '/convite/$token'
    | '/admin/acessos'
    | '/admin/cardapios'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/dicas'
    | '/admin/ebooks'
    | '/admin/eventos'
    | '/admin/interesses'
    | '/admin/leads'
    | '/admin/notificacoes'
    | '/admin/parceiros'
    | '/admin/portfolio'
    | '/admin/referencias'
    | '/admin/upgrades'
    | '/app/cardapios'
    | '/app/checklist'
    | '/app/convites'
    | '/app/dicas'
    | '/app/ebook'
    | '/app/parceiros'
    | '/app/pendencias'
    | '/app/portfolio'
    | '/app/referencias'
    | '/app/upgrades'
    | '/convite/padrinho/$token'
    | '/convite/preview/$invitationId'
    | '/admin/'
    | '/app/'
    | '/admin/checklist/$eventId'
    | '/admin/convites/$eventId'
    | '/admin/leads/candidaturas'
    | '/admin/leads/formulario'
    | '/admin/leads/integracoes'
    | '/admin/leads/parceiros'
    | '/admin/checklist/'
    | '/admin/convites/'
    | '/admin/leads/'
    | '/admin/leads/formulario/diagnostico'
    | '/admin/leads/formulario/pixels'
    | '/admin/leads/formulario/score'
    | '/admin/leads/formulario/simulador'
    | '/admin/leads/formulario/visual'
    | '/admin/leads/formulario/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leads'
    | '/login'
    | '/seja-parceiro'
    | '/trabalhe-conosco'
    | '/convite/$token'
    | '/admin/acessos'
    | '/admin/cardapios'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/dicas'
    | '/admin/ebooks'
    | '/admin/eventos'
    | '/admin/interesses'
    | '/admin/notificacoes'
    | '/admin/parceiros'
    | '/admin/portfolio'
    | '/admin/referencias'
    | '/admin/upgrades'
    | '/app/cardapios'
    | '/app/checklist'
    | '/app/convites'
    | '/app/dicas'
    | '/app/ebook'
    | '/app/parceiros'
    | '/app/pendencias'
    | '/app/portfolio'
    | '/app/referencias'
    | '/app/upgrades'
    | '/convite/padrinho/$token'
    | '/convite/preview/$invitationId'
    | '/admin'
    | '/app'
    | '/admin/checklist/$eventId'
    | '/admin/convites/$eventId'
    | '/admin/leads/candidaturas'
    | '/admin/leads/integracoes'
    | '/admin/leads/parceiros'
    | '/admin/checklist'
    | '/admin/convites'
    | '/admin/leads'
    | '/admin/leads/formulario/diagnostico'
    | '/admin/leads/formulario/pixels'
    | '/admin/leads/formulario/score'
    | '/admin/leads/formulario/simulador'
    | '/admin/leads/formulario/visual'
    | '/admin/leads/formulario'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/leads'
    | '/login'
    | '/seja-parceiro'
    | '/trabalhe-conosco'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/convite/$token'
    | '/_authenticated/admin/acessos'
    | '/_authenticated/admin/cardapios'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/dicas'
    | '/_authenticated/admin/ebooks'
    | '/_authenticated/admin/eventos'
    | '/_authenticated/admin/interesses'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/notificacoes'
    | '/_authenticated/admin/parceiros'
    | '/_authenticated/admin/portfolio'
    | '/_authenticated/admin/referencias'
    | '/_authenticated/admin/upgrades'
    | '/_authenticated/app/cardapios'
    | '/_authenticated/app/checklist'
    | '/_authenticated/app/convites'
    | '/_authenticated/app/dicas'
    | '/_authenticated/app/ebook'
    | '/_authenticated/app/parceiros'
    | '/_authenticated/app/pendencias'
    | '/_authenticated/app/portfolio'
    | '/_authenticated/app/referencias'
    | '/_authenticated/app/upgrades'
    | '/convite/padrinho/$token'
    | '/convite/preview/$invitationId'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/admin/checklist/$eventId'
    | '/_authenticated/admin/convites/$eventId'
    | '/_authenticated/admin/leads/candidaturas'
    | '/_authenticated/admin/leads/formulario'
    | '/_authenticated/admin/leads/integracoes'
    | '/_authenticated/admin/leads/parceiros'
    | '/_authenticated/admin/checklist/'
    | '/_authenticated/admin/convites/'
    | '/_authenticated/admin/leads/'
    | '/_authenticated/admin/leads/formulario/diagnostico'
    | '/_authenticated/admin/leads/formulario/pixels'
    | '/_authenticated/admin/leads/formulario/score'
    | '/_authenticated/admin/leads/formulario/simulador'
    | '/_authenticated/admin/leads/formulario/visual'
    | '/_authenticated/admin/leads/formulario/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  SejaParceiroRoute: typeof SejaParceiroRoute
  TrabalheConoscoRoute: typeof TrabalheConoscoRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  ConvitePadrinhoTokenRoute: typeof ConvitePadrinhoTokenRoute
  ConvitePreviewInvitationIdRoute: typeof ConvitePreviewInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabalhe-conosco': {
      id: '/trabalhe-conosco'
      path: '/trabalhe-conosco'
      fullPath: '/trabalhe-conosco'
      preLoaderRoute: typeof TrabalheConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seja-parceiro': {
      id: '/seja-parceiro'
      path: '/seja-parceiro'
      fullPath: '/seja-parceiro'
      preLoaderRoute: typeof SejaParceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/convite/preview/$invitationId': {
      id: '/convite/preview/$invitationId'
      path: '/convite/preview/$invitationId'
      fullPath: '/convite/preview/$invitationId'
      preLoaderRoute: typeof ConvitePreviewInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/padrinho/$token': {
      id: '/convite/padrinho/$token'
      path: '/convite/padrinho/$token'
      fullPath: '/convite/padrinho/$token'
      preLoaderRoute: typeof ConvitePadrinhoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/upgrades': {
      id: '/_authenticated/app/upgrades'
      path: '/upgrades'
      fullPath: '/app/upgrades'
      preLoaderRoute: typeof AuthenticatedAppUpgradesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/referencias': {
      id: '/_authenticated/app/referencias'
      path: '/referencias'
      fullPath: '/app/referencias'
      preLoaderRoute: typeof AuthenticatedAppReferenciasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/portfolio': {
      id: '/_authenticated/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AuthenticatedAppPortfolioRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pendencias': {
      id: '/_authenticated/app/pendencias'
      path: '/pendencias'
      fullPath: '/app/pendencias'
      preLoaderRoute: typeof AuthenticatedAppPendenciasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/parceiros': {
      id: '/_authenticated/app/parceiros'
      path: '/parceiros'
      fullPath: '/app/parceiros'
      preLoaderRoute: typeof AuthenticatedAppParceirosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ebook': {
      id: '/_authenticated/app/ebook'
      path: '/ebook'
      fullPath: '/app/ebook'
      preLoaderRoute: typeof AuthenticatedAppEbookRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dicas': {
      id: '/_authenticated/app/dicas'
      path: '/dicas'
      fullPath: '/app/dicas'
      preLoaderRoute: typeof AuthenticatedAppDicasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/convites': {
      id: '/_authenticated/app/convites'
      path: '/convites'
      fullPath: '/app/convites'
      preLoaderRoute: typeof AuthenticatedAppConvitesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/checklist': {
      id: '/_authenticated/app/checklist'
      path: '/checklist'
      fullPath: '/app/checklist'
      preLoaderRoute: typeof AuthenticatedAppChecklistRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cardapios': {
      id: '/_authenticated/app/cardapios'
      path: '/cardapios'
      fullPath: '/app/cardapios'
      preLoaderRoute: typeof AuthenticatedAppCardapiosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/upgrades': {
      id: '/_authenticated/admin/upgrades'
      path: '/upgrades'
      fullPath: '/admin/upgrades'
      preLoaderRoute: typeof AuthenticatedAdminUpgradesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/referencias': {
      id: '/_authenticated/admin/referencias'
      path: '/referencias'
      fullPath: '/admin/referencias'
      preLoaderRoute: typeof AuthenticatedAdminReferenciasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/portfolio': {
      id: '/_authenticated/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AuthenticatedAdminPortfolioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parceiros': {
      id: '/_authenticated/admin/parceiros'
      path: '/parceiros'
      fullPath: '/admin/parceiros'
      preLoaderRoute: typeof AuthenticatedAdminParceirosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notificacoes': {
      id: '/_authenticated/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AuthenticatedAdminNotificacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/interesses': {
      id: '/_authenticated/admin/interesses'
      path: '/interesses'
      fullPath: '/admin/interesses'
      preLoaderRoute: typeof AuthenticatedAdminInteressesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ebooks': {
      id: '/_authenticated/admin/ebooks'
      path: '/ebooks'
      fullPath: '/admin/ebooks'
      preLoaderRoute: typeof AuthenticatedAdminEbooksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dicas': {
      id: '/_authenticated/admin/dicas'
      path: '/dicas'
      fullPath: '/admin/dicas'
      preLoaderRoute: typeof AuthenticatedAdminDicasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cardapios': {
      id: '/_authenticated/admin/cardapios'
      path: '/cardapios'
      fullPath: '/admin/cardapios'
      preLoaderRoute: typeof AuthenticatedAdminCardapiosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/acessos': {
      id: '/_authenticated/admin/acessos'
      path: '/acessos'
      fullPath: '/admin/acessos'
      preLoaderRoute: typeof AuthenticatedAdminAcessosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads/': {
      id: '/_authenticated/admin/leads/'
      path: '/'
      fullPath: '/admin/leads/'
      preLoaderRoute: typeof AuthenticatedAdminLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminLeadsRoute
    }
    '/_authenticated/admin/convites/': {
      id: '/_authenticated/admin/convites/'
      path: '/convites'
      fullPath: '/admin/convites/'
      preLoaderRoute: typeof AuthenticatedAdminConvitesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/checklist/': {
      id: '/_authenticated/admin/checklist/'
      path: '/checklist'
      fullPath: '/admin/checklist/'
      preLoaderRoute: typeof AuthenticatedAdminChecklistIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads/parceiros': {
      id: '/_authenticated/admin/leads/parceiros'
      path: '/parceiros'
      fullPath: '/admin/leads/parceiros'
      preLoaderRoute: typeof AuthenticatedAdminLeadsParceirosRouteImport
      parentRoute: typeof AuthenticatedAdminLeadsRoute
    }
    '/_authenticated/admin/leads/integracoes': {
      id: '/_authenticated/admin/leads/integracoes'
      path: '/integracoes'
      fullPath: '/admin/leads/integracoes'
      preLoaderRoute: typeof AuthenticatedAdminLeadsIntegracoesRouteImport
      parentRoute: typeof AuthenticatedAdminLeadsRoute
    }
    '/_authenticated/admin/leads/formulario': {
      id: '/_authenticated/admin/leads/formulario'
      path: '/formulario'
      fullPath: '/admin/leads/formulario'
      preLoaderRoute: typeof AuthenticatedAdminLeadsFormularioRouteImport
      parentRoute: typeof AuthenticatedAdminLeadsRoute
    }
    '/_authenticated/admin/leads/candidaturas': {
      id: '/_authenticated/admin/leads/candidaturas'
      path: '/candidaturas'
      fullPath: '/admin/leads/candidaturas'
      preLoaderRoute: typeof AuthenticatedAdminLeadsCandidaturasRouteImport
      parentRoute: typeof AuthenticatedAdminLeadsRoute
    }
    '/_authenticated/admin/convites/$eventId': {
      id: '/_authenticated/admin/convites/$eventId'
      path: '/convites/$eventId'
      fullPath: '/admin/convites/$eventId'
      preLoaderRoute: typeof AuthenticatedAdminConvitesEventIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/checklist/$eventId': {
      id: '/_authenticated/admin/checklist/$eventId'
      path: '/checklist/$eventId'
      fullPath: '/admin/checklist/$eventId'
      preLoaderRoute: typeof AuthenticatedAdminChecklistEventIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads/formulario/': {
      id: '/_authenticated/admin/leads/formulario/'
      path: '/'
      fullPath: '/admin/leads/formulario/'
      preLoaderRoute: typeof AuthenticatedAdminLeadsFormularioIndexRouteImport
      parentRoute: typeof AuthenticatedAdminLeadsFormularioRoute
    }
    '/_authenticated/admin/leads/formulario/visual': {
      id: '/_authenticated/admin/leads/formulario/visual'
      path: '/visual'
      fullPath: '/admin/leads/formulario/visual'
      preLoaderRoute: typeof AuthenticatedAdminLeadsFormularioVisualRouteImport
      parentRoute: typeof AuthenticatedAdminLeadsFormularioRoute
    }
    '/_authenticated/admin/leads/formulario/simulador': {
      id: '/_authenticated/admin/leads/formulario/simulador'
      path: '/simulador'
      fullPath: '/admin/leads/formulario/simulador'
      preLoaderRoute: typeof AuthenticatedAdminLeadsFormularioSimuladorRouteImport
      parentRoute: typeof AuthenticatedAdminLeadsFormularioRoute
    }
    '/_authenticated/admin/leads/formulario/score': {
      id: '/_authenticated/admin/leads/formulario/score'
      path: '/score'
      fullPath: '/admin/leads/formulario/score'
      preLoaderRoute: typeof AuthenticatedAdminLeadsFormularioScoreRouteImport
      parentRoute: typeof AuthenticatedAdminLeadsFormularioRoute
    }
    '/_authenticated/admin/leads/formulario/pixels': {
      id: '/_authenticated/admin/leads/formulario/pixels'
      path: '/pixels'
      fullPath: '/admin/leads/formulario/pixels'
      preLoaderRoute: typeof AuthenticatedAdminLeadsFormularioPixelsRouteImport
      parentRoute: typeof AuthenticatedAdminLeadsFormularioRoute
    }
    '/_authenticated/admin/leads/formulario/diagnostico': {
      id: '/_authenticated/admin/leads/formulario/diagnostico'
      path: '/diagnostico'
      fullPath: '/admin/leads/formulario/diagnostico'
      preLoaderRoute: typeof AuthenticatedAdminLeadsFormularioDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedAdminLeadsFormularioRoute
    }
  }
}

interface AuthenticatedAdminLeadsFormularioRouteChildren {
  AuthenticatedAdminLeadsFormularioDiagnosticoRoute: typeof AuthenticatedAdminLeadsFormularioDiagnosticoRoute
  AuthenticatedAdminLeadsFormularioPixelsRoute: typeof AuthenticatedAdminLeadsFormularioPixelsRoute
  AuthenticatedAdminLeadsFormularioScoreRoute: typeof AuthenticatedAdminLeadsFormularioScoreRoute
  AuthenticatedAdminLeadsFormularioSimuladorRoute: typeof AuthenticatedAdminLeadsFormularioSimuladorRoute
  AuthenticatedAdminLeadsFormularioVisualRoute: typeof AuthenticatedAdminLeadsFormularioVisualRoute
  AuthenticatedAdminLeadsFormularioIndexRoute: typeof AuthenticatedAdminLeadsFormularioIndexRoute
}

const AuthenticatedAdminLeadsFormularioRouteChildren: AuthenticatedAdminLeadsFormularioRouteChildren =
  {
    AuthenticatedAdminLeadsFormularioDiagnosticoRoute:
      AuthenticatedAdminLeadsFormularioDiagnosticoRoute,
    AuthenticatedAdminLeadsFormularioPixelsRoute:
      AuthenticatedAdminLeadsFormularioPixelsRoute,
    AuthenticatedAdminLeadsFormularioScoreRoute:
      AuthenticatedAdminLeadsFormularioScoreRoute,
    AuthenticatedAdminLeadsFormularioSimuladorRoute:
      AuthenticatedAdminLeadsFormularioSimuladorRoute,
    AuthenticatedAdminLeadsFormularioVisualRoute:
      AuthenticatedAdminLeadsFormularioVisualRoute,
    AuthenticatedAdminLeadsFormularioIndexRoute:
      AuthenticatedAdminLeadsFormularioIndexRoute,
  }

const AuthenticatedAdminLeadsFormularioRouteWithChildren =
  AuthenticatedAdminLeadsFormularioRoute._addFileChildren(
    AuthenticatedAdminLeadsFormularioRouteChildren,
  )

interface AuthenticatedAdminLeadsRouteChildren {
  AuthenticatedAdminLeadsCandidaturasRoute: typeof AuthenticatedAdminLeadsCandidaturasRoute
  AuthenticatedAdminLeadsFormularioRoute: typeof AuthenticatedAdminLeadsFormularioRouteWithChildren
  AuthenticatedAdminLeadsIntegracoesRoute: typeof AuthenticatedAdminLeadsIntegracoesRoute
  AuthenticatedAdminLeadsParceirosRoute: typeof AuthenticatedAdminLeadsParceirosRoute
  AuthenticatedAdminLeadsIndexRoute: typeof AuthenticatedAdminLeadsIndexRoute
}

const AuthenticatedAdminLeadsRouteChildren: AuthenticatedAdminLeadsRouteChildren =
  {
    AuthenticatedAdminLeadsCandidaturasRoute:
      AuthenticatedAdminLeadsCandidaturasRoute,
    AuthenticatedAdminLeadsFormularioRoute:
      AuthenticatedAdminLeadsFormularioRouteWithChildren,
    AuthenticatedAdminLeadsIntegracoesRoute:
      AuthenticatedAdminLeadsIntegracoesRoute,
    AuthenticatedAdminLeadsParceirosRoute:
      AuthenticatedAdminLeadsParceirosRoute,
    AuthenticatedAdminLeadsIndexRoute: AuthenticatedAdminLeadsIndexRoute,
  }

const AuthenticatedAdminLeadsRouteWithChildren =
  AuthenticatedAdminLeadsRoute._addFileChildren(
    AuthenticatedAdminLeadsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAcessosRoute: typeof AuthenticatedAdminAcessosRoute
  AuthenticatedAdminCardapiosRoute: typeof AuthenticatedAdminCardapiosRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminDicasRoute: typeof AuthenticatedAdminDicasRoute
  AuthenticatedAdminEbooksRoute: typeof AuthenticatedAdminEbooksRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
  AuthenticatedAdminInteressesRoute: typeof AuthenticatedAdminInteressesRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRouteWithChildren
  AuthenticatedAdminNotificacoesRoute: typeof AuthenticatedAdminNotificacoesRoute
  AuthenticatedAdminParceirosRoute: typeof AuthenticatedAdminParceirosRoute
  AuthenticatedAdminPortfolioRoute: typeof AuthenticatedAdminPortfolioRoute
  AuthenticatedAdminReferenciasRoute: typeof AuthenticatedAdminReferenciasRoute
  AuthenticatedAdminUpgradesRoute: typeof AuthenticatedAdminUpgradesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminChecklistEventIdRoute: typeof AuthenticatedAdminChecklistEventIdRoute
  AuthenticatedAdminConvitesEventIdRoute: typeof AuthenticatedAdminConvitesEventIdRoute
  AuthenticatedAdminChecklistIndexRoute: typeof AuthenticatedAdminChecklistIndexRoute
  AuthenticatedAdminConvitesIndexRoute: typeof AuthenticatedAdminConvitesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAcessosRoute: AuthenticatedAdminAcessosRoute,
  AuthenticatedAdminCardapiosRoute: AuthenticatedAdminCardapiosRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminDicasRoute: AuthenticatedAdminDicasRoute,
  AuthenticatedAdminEbooksRoute: AuthenticatedAdminEbooksRoute,
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
  AuthenticatedAdminInteressesRoute: AuthenticatedAdminInteressesRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRouteWithChildren,
  AuthenticatedAdminNotificacoesRoute: AuthenticatedAdminNotificacoesRoute,
  AuthenticatedAdminParceirosRoute: AuthenticatedAdminParceirosRoute,
  AuthenticatedAdminPortfolioRoute: AuthenticatedAdminPortfolioRoute,
  AuthenticatedAdminReferenciasRoute: AuthenticatedAdminReferenciasRoute,
  AuthenticatedAdminUpgradesRoute: AuthenticatedAdminUpgradesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminChecklistEventIdRoute:
    AuthenticatedAdminChecklistEventIdRoute,
  AuthenticatedAdminConvitesEventIdRoute:
    AuthenticatedAdminConvitesEventIdRoute,
  AuthenticatedAdminChecklistIndexRoute: AuthenticatedAdminChecklistIndexRoute,
  AuthenticatedAdminConvitesIndexRoute: AuthenticatedAdminConvitesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCardapiosRoute: typeof AuthenticatedAppCardapiosRoute
  AuthenticatedAppChecklistRoute: typeof AuthenticatedAppChecklistRoute
  AuthenticatedAppConvitesRoute: typeof AuthenticatedAppConvitesRoute
  AuthenticatedAppDicasRoute: typeof AuthenticatedAppDicasRoute
  AuthenticatedAppEbookRoute: typeof AuthenticatedAppEbookRoute
  AuthenticatedAppParceirosRoute: typeof AuthenticatedAppParceirosRoute
  AuthenticatedAppPendenciasRoute: typeof AuthenticatedAppPendenciasRoute
  AuthenticatedAppPortfolioRoute: typeof AuthenticatedAppPortfolioRoute
  AuthenticatedAppReferenciasRoute: typeof AuthenticatedAppReferenciasRoute
  AuthenticatedAppUpgradesRoute: typeof AuthenticatedAppUpgradesRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCardapiosRoute: AuthenticatedAppCardapiosRoute,
  AuthenticatedAppChecklistRoute: AuthenticatedAppChecklistRoute,
  AuthenticatedAppConvitesRoute: AuthenticatedAppConvitesRoute,
  AuthenticatedAppDicasRoute: AuthenticatedAppDicasRoute,
  AuthenticatedAppEbookRoute: AuthenticatedAppEbookRoute,
  AuthenticatedAppParceirosRoute: AuthenticatedAppParceirosRoute,
  AuthenticatedAppPendenciasRoute: AuthenticatedAppPendenciasRoute,
  AuthenticatedAppPortfolioRoute: AuthenticatedAppPortfolioRoute,
  AuthenticatedAppReferenciasRoute: AuthenticatedAppReferenciasRoute,
  AuthenticatedAppUpgradesRoute: AuthenticatedAppUpgradesRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  SejaParceiroRoute: SejaParceiroRoute,
  TrabalheConoscoRoute: TrabalheConoscoRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  ConvitePadrinhoTokenRoute: ConvitePadrinhoTokenRoute,
  ConvitePreviewInvitationIdRoute: ConvitePreviewInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
